### ISSUE TITLE
GITHUB action to zip H2GIS SNAPSHOT with its dependencies

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1219]
Add a github action to publish a zipped version of H2GIS SNAPSHOT

**Comment by ebocher** [comment]
I propose to publish a zipped version as we do for geoclimate for the JOSS paper 
See here : 
https://github.com/orbisgis/geoclimate/actions/runs/1498867110

**Comment by j3r3m1** [comment]
It would definitely be nice for me

**Comment by ebocher** [comment]
@SPalominos 
Is it possible to plan this issue ?

**Comment by SPalominos** [comment]
@j3r3m1 @ebocher  Here is the link to the last snapshot : https://nightly.link/orbisgis/h2gis/workflows/CI_snapshot/master/h2gis-standalone-bin.zip

**Comment by j3r3m1** [comment]
Cool ! Thanks !

**Comment by nicolas-f** [comment]
Its weird, there is a zip file into this zip file

**Comment by ebocher** [comment]
Good catch @nicolas-f 
@SPalominos  when you have time ;-)

**Comment by ebocher** [comment]
Any plan to fix it ?

**Comment by SPalominos** [comment]
Yes, today ;)

**Comment by j3r3m1** [comment]
There is still a zip in the zip =)

**Comment by ebocher** [comment]
Any input  ?

**Comment by nicolas-f** [comment]
Related to
https://github.com/actions/upload-artifact/issues/39

**Comment by nicolas-f** [comment]
I think we should unzip ```h2gis-standalone-bin.zip``` then provide the folder to upload-artifact,it will create the zip itself.
```yml

      - name: Archive production artifacts
        run: unzip h2gis-dist/target/h2gis-standalone-bin.zip
        uses: actions/upload-artifact@v2
        with:
          name: h2gis-standalone-bin
          path: /home/nicolas/github/h2gis/h2gis-dist/target/h2gis-standalone-bin
```
